Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,57 +32,46 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
 
-        run: >-                
-DEFAULT_SKMS_URL='stage.dev.skms.adobe.com'
-
-function skms_request() {
-	local username=$1
-	local passkey=$2
-	local object=$3
-	local method=$4
-	local method_params=$5
-	local url=$6
-
-	if [ -z "$username" ]; then
-		echo "First parameter missing, must be SKMS username"
-		return 1
-	fi
-
-	if [ -z "$passkey" ]; then
-		echo "Second parameter missing, must be SKMS passkey"
-		return 1
-	fi
-
-	if [ -z "$object" ]; then
-		echo "Third parameter missing, must be an SKMS dao object"
-		return 1
-	fi
-
-	if [ -z "$method" ]; then
-		echo "Fourth parameter missing, must be SKMS dao method"
-		return 1
-	fi
-
-	if [ -z "$method_params" ]; then
-		method_params='{}'
-	fi
-
-	if [ -z "$url" ]; then
-		url=$DEFAULT_SKMS_URL
-	fi
-
-	if ! type "jq" >/dev/null; then
-		echo "jq is required but not installed"
-	fi
-
-	if ! type "curl" >/dev/null; then
-		echo "curl is required but not installed"
-	fi
-
-	local params="{\"_username\":\"${username}\",\"_passkey\":\"${passkey}\",\"_object\":\"${object}\",\"_method\": \"${method}\"}"
-	params=$(echo "$params $method_params" | jq -s add)
-
-	curl https://${url}/web_api --data-urlencode "_parameters=${params}"
-	echo ''
-}
-skms_request wp-adobecom-chimera_cmr_skms_api_user '${{ secrets.SKMS_DEV }}' CmrDao createCmr '{"change_executor":"jmichnow","change_model":655075,"maintenance_type":"internal_change","maintenance_window_end_time":"2023-04-04 12:00","maintenance_window_start_time":"2023-04-04 10:00","priority":"normal","save_as_draft":false,"summary":"chimera release"}' 
+        run: |              
+          DEFAULT_SKMS_URL='stage.dev.skms.adobe.com'
+          function skms_request() {
+          	local username=$1
+          	local passkey=$2
+          	local object=$3
+          	local method=$4
+          	local method_params=$5
+          	local url=$6
+          	if [ -z "$username" ]; then
+          		echo "First parameter missing, must be SKMS username"
+          		return 1
+          	fi          
+          	if [ -z "$passkey" ]; then
+          		echo "Second parameter missing, must be SKMS passkey"
+	          	return 1
+          	fi
+          	if [ -z "$object" ]; then
+	          	echo "Third parameter missing, must be an SKMS dao object"
+          		return 1
+          	fi
+          	if [ -z "$method" ]; then
+	          	echo "Fourth parameter missing, must be SKMS dao method"
+          		return 1
+          	fi
+          	if [ -z "$method_params" ]; then
+	          	method_params='{}'
+          	fi
+          	if [ -z "$url" ]; then
+	          	url=$DEFAULT_SKMS_URL
+          	fi
+          	if ! type "jq" >/dev/null; then
+          		echo "jq is required but not installed"
+          	fi
+          	if ! type "curl" >/dev/null; then
+	          	echo "curl is required but not installed"
+          	fi
+          	local params="{\"_username\":\"${username}\",\"_passkey\":\"${passkey}\",\"_object\":\"${object}\",\"_method\": \"${method}\"}"
+          	params=$(echo "$params $method_params" | jq -s add)
+          	curl https://${url}/web_api --data-urlencode "_parameters=${params}"
+          	echo ''
+          }
+          skms_request wp-adobecom-chimera_cmr_skms_api_user '${{ secrets.SKMS_DEV }}' CmrDao createCmr '{"change_executor":"jmichnow","change_model":655075,"maintenance_type":"internal_change","maintenance_window_end_time":"2023-04-04 12:00","maintenance_window_start_time":"2023-04-04 10:00","priority":"normal","save_as_draft":false,"summary":"chimera release"}' 
